=== esmerado/Javier_Esmerado_Vela__LE_I.E.4.1/Actv1/Actv1.dtd
<!ELEMENT cd (cancion*, songs*)>
<!ELEMENT songs (song*)>
<!ATTLIST cd titulo CDATA #REQUIRED>
<!ELEMENT song (cancion)>
<!ELEMENT cancion (titulo, compositores, productores, sello, artista, fecha*)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT compositores (compositor)>
<!ELEMENT compositor (nombres+, apellidos+)>
<!ELEMENT nombres (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT productores (productor)>
<!ELEMENT productor (nombres+, apellidos+)>
<!ELEMENT fecha EMPTY>
<!ATTLIST fecha dia CDATA #REQUIRED>
<!ATTLIST fecha anio CDATA #REQUIRED>
<!ATTLIST fecha mes CDATA #REQUIRED>
<!ELEMENT sello (#PCDATA)>
<!ELEMENT artista (#PCDATA)>

=== esmerado/Javier_Esmerado_Vela__LE_I.E.4.1/Actv1/Actv1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cd SYSTEM "Actv1.dtd">
<cd titulo="mi cd">
<songs>
<song>
<cancion>
  <titulo>Give it 2 me</titulo>
  <compositores>
    <compositor>
      <nombres>Pharrel</nombres>
      <apellidos>Williams</apellidos>
    </compositor>
  </compositores>
  <productores>
    <productor>
      <nombres>Pharrel</nombres>
      <apellidos>Williams</apellidos>
    </productor>
  </productores>
  <sello>Warner Bros Record</sello>
  <artista>Madonna</artista>
  <fecha dia="25" anio="2002" mes="Noviembre"/>
</cancion>
</song>
</songs>
</cd>
