=== esmerado/Javier_Esmerado_Vela__LE_I.E.4.1/Actv7/Actv7.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Libro">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="Titulo"/>
                <xs:element name="Contenido">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded" minOccurs="0">
                            <xs:element name="Capitulo" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="Tema"/>
                                        <xs:element name="Seccion" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute type="xs:byte" name="apartados" use="optional"/>
                                                        <xs:attribute type="xs:string" name="dificil" use="optional"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="materia" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Separacion">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="Tema" minOccurs="0"/>
                                        <xs:element name="Seccion" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute type="xs:byte" name="apartados" use="optional"/>
                                                        <xs:attribute type="xs:string" name="dificil" use="optional"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="materia" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element type="xs:string" name="Copyright"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== esmerado/Javier_Esmerado_Vela__LE_I.E.4.1/Actv7/Actv7.xml
<?xml version="1.0" encoding="UTF-8"?>
<Libro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Actv7.xsd">

<Titulo>Java y XML</Titulo>
    <Contenido>
        <Capitulo materia="XML">
            <Tema>Introducción</Tema>
            <Seccion apartados="7">Qué es</Seccion>
            <Seccion apartados="3">Cómo se usa</Seccion>
        </Capitulo>
        <Capitulo materia="XML">
            <Tema>Creando XML</Tema>
            <Seccion apartados="0">Un documento XML</Seccion>
            <Seccion apartados="2">La cabecera</Seccion>
            <Seccion apartados="6">El contenido</Seccion>
        </Capitulo>
        <Capitulo>

            ESCUELAS SALESIANAS Ma AUXILIADORA
            C/ Santa Ma Mazzarello, 1
            41005- Sevilla
            Tlf: 954 63 23 47
            www.nervion.salesianas.com

            LENGUAJE DE MARCAS 1o DAM
            2020-2021

            <Tema>Analizando XML</Tema>
            <Seccion apartados="3">Preparación</Seccion>
            <Seccion apartados="3" dificil="true">SAX</Seccion>
            <Seccion apartados="9" dificil="true">Manejadores</Seccion>
            <Seccion apartados="0">Una forma mejor de cargar el analizador</Seccion>
        </Capitulo>
        <Separacion/>
        <Capitulo materia="Java">
            <Tema>JDOM</Tema>
            <Seccion apartados="2">Introducción</Seccion>
            <Seccion apartados="4" dificil="true">DOM&amp;JDOM</Seccion>
        </Capitulo>
    </Contenido>
    <Copyright>OReillyCopyright</Copyright>
</Libro>
