=== esmerado/Javier_Esmerado_Vela__LE_I.E.4.1/Actv9/Actv9.dtd
<!ELEMENT empresa (sucursal+)>
<!ELEMENT sucursal (zonaGestion+, zonaExposicion+)>
<!ELEMENT zonaGestion (pago+, albaran+)>
<!ELEMENT zonaExposicion (articulos+)>
<!ELEMENT pago (#PCDATA)>
<!ELEMENT albaran (codigoPedido+, nombre+, fecha+, observacion+, plazoRevision+)>
<!ELEMENT articulos (codigo+, numArticulos+, precioUnidad+, observaciones+)>
<!ELEMENT codigoPedido (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT observacion (urgente | incompleto)>
<!ELEMENT urgente EMPTY>
<!ELEMENT incompleto EMPTY>
<!ELEMENT plazoRevision (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT numArticulos (#PCDATA)>
<!ELEMENT precioUnidad (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>

=== esmerado/Javier_Esmerado_Vela__LE_I.E.4.1/Actv9/Actv9_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresa SYSTEM "Actv9.dtd">
<empresa>
    <sucursal>
        <zonaGestion>
            <pago>20€</pago>
            <albaran>
                <codigoPedido>ABC-123</codigoPedido>
                <nombre>Javier</nombre>
                <fecha>2020-02-10</fecha>
                <observacion>
                    <incompleto/>
                </observacion>
                <plazoRevision>10</plazoRevision>
            </albaran>
        </zonaGestion>
        <zonaExposicion>
            <articulos>
                <codigo>A123456</codigo>
                <numArticulos>12</numArticulos>
                <precioUnidad>20€</precioUnidad>
                <observaciones>Esto es una prueba de observacion</observaciones>
            </articulos>
        </zonaExposicion>
    </sucursal>
</empresa>
