=== esmerado/Javier_Esmerado_Vela__LE_I.E.4.1/Actv3/Actv3.dtd
<!ELEMENT motores (piezas*, seccion, empleado*)>
<!ELEMENT piezas (otraspiezas*)>
<!ELEMENT otraspiezas (importantes*, secundarias*)>
<!ELEMENT importantes (#PCDATA)>
<!ELEMENT secundarias (#PCDATA)>
<!ELEMENT seccion (#PCDATA)>
<!ELEMENT empleado (responsable, familiares*)>
<!ELEMENT responsable (#PCDATA)>
<!ELEMENT familiares (madre, padre, hermano*)>
<!ELEMENT madre (#PCDATA)>
<!ELEMENT padre (#PCDATA)>
<!ELEMENT hermano (#PCDATA)>

=== esmerado/Javier_Esmerado_Vela__LE_I.E.4.1/Actv3/Actv3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE motores SYSTEM "Actv3.dtd">
<motores>
    <piezas>
        <otraspiezas>
            <importantes>Manguito</importantes>
            <secundarias>Engranaje</secundarias>
        </otraspiezas>
    </piezas>
    <seccion>Lujo</seccion>
    <empleado>
        <responsable>Javier Esmerado</responsable>
        <familiares>
            <madre>Susana</madre>
            <padre>Vivente</padre>
            <hermano>Pablo</hermano>
        </familiares>
    </empleado>
</motores>
