=== esmerado/Javier_Esmerado_Vela__LE_I.E.4.1/Actv4/Actv4.dtd
<!ELEMENT universidad (alumnos*, profesores*, asignaturas*)>
        <!ELEMENT alumnos (DNI, pasaporte, nombre, (apellidos | apellido), fechanacimiento,(direccionpostal,telefonos, correo, asignaturasalumnos)?)>
        <!ELEMENT DNI (#PCDATA)>
        <!ELEMENT pasaporte (pais)>
        <!ELEMENT pais (#PCDATA)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT apellidos (#PCDATA)>
        <!ELEMENT apellido (#PCDATA)>
        <!ELEMENT fechanacimiento (#PCDATA)>
        <!ELEMENT direccionpostal (#PCDATA)>
        <!ELEMENT telefonos (#PCDATA)>
        <!ELEMENT correo (#PCDATA)>
        <!ELEMENT asignaturasalumnos EMPTY>
        <!ATTLIST asignaturasalumnos materia CDATA #REQUIRED>
        <!ATTLIST asignaturasalumnos notas (NP | SS | AP | NT | SB | MH) #REQUIRED>
        <!ELEMENT notas (#PCDATA)>
        <!ELEMENT profesores (DNI, pasaporte, nombre, (apellidos | apellido), fechanacimiento, direccionpostal+, telefonos+, correo+, despacho, tutorias, asignaturasprofesor+)>
        <!ELEMENT despacho (#PCDATA)>
        <!ELEMENT tutorias (#PCDATA)>
        <!ELEMENT asignaturasprofesor (#PCDATA)>
        <!ELEMENT asignaturas (codigo, numerocreditos+, carrera, curso+, caracteristicas)>
        <!ELEMENT caracteristicas EMPTY>
        <!ATTLIST caracteristicas tiempo (optativa | libreleccion) #REQUIRED>
        <!ELEMENT codigo (#PCDATA)>
        <!ELEMENT numerocreditos (#PCDATA)>
        <!ELEMENT carrera (#PCDATA)>
        <!ELEMENT curso (#PCDATA)>

=== esmerado/Javier_Esmerado_Vela__LE_I.E.4.1/Actv4/Actv4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE universidad SYSTEM "Actv4.dtd">
<universidad>
    <alumnos>
        <DNI>77822787X</DNI>
        <pasaporte>
            <pais>Espa침a</pais>
        </pasaporte>
        <nombre>Javier</nombre>
        <apellidos>Esmerado Vela</apellidos>
        <fechanacimiento>22/03/2002</fechanacimiento>
        <direccionpostal>Don Alonso Quijano</direccionpostal>
        <telefonos>647333523</telefonos>
        <correo>esmerado.vela.javier@gmail.com</correo>
        <asignaturasalumnos materia="MATES" notas="SB"/>
    </alumnos>
    <profesores>
        <DNI>12345678X</DNI>
        <pasaporte>
            <pais>Espa침a</pais>
        </pasaporte>
        <nombre>Pablo</nombre>
        <apellido>Esmerado</apellido>
        <fechanacimiento>22/03/2002</fechanacimiento>
        <direccionpostal>Don Alosno Quijano </direccionpostal>
        <telefonos>647333523</telefonos>
        <correo>esme@gmail.com</correo>
        <despacho>1</despacho>
        <tutorias>1</tutorias>
        <asignaturasprofesor>Programaci칩n</asignaturasprofesor>
    </profesores>
    <asignaturas>
        <codigo>12345</codigo>
        <numerocreditos>5</numerocreditos>
        <carrera>Inform치tic</carrera>
        <curso>Desarrollo Web</curso>
        <caracteristicas tiempo="optativa"/>
    </asignaturas>
</universidad>
